# Notebook 3: Exploratory Data Analysis (EDA)

### Objective
Explore the cleaned dark store dataset to understand the distribution of stores, identify trends across brands, and generate initial business insights through descriptive statistics and visualizations.

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving clean_darkstores.csv to clean_darkstores (2).csv

In [ ]:
stores = pd.read_csv("clean_darkstores.csv")

In [ ]:
stores.head()

      id  accuracy  latitude  longitude    brand name city state locality
0  42985      43.0  8.478260  76.954711  Blinkit  NaN  NaN   NaN      NaN
1  40038      13.0  8.525199  76.955395  Blinkit  NaN  NaN   NaN      NaN
2  38514      30.0  9.587031  76.535782  Blinkit  NaN  NaN   NaN      NaN
3  38406      48.0  9.922391  78.095686  Blinkit  NaN  NaN   NaN      NaN
4  39056       0.0  9.949993  76.253442  Blinkit  NaN  NaN   NaN      NaN

In [ ]:
stores.describe(include="all")

,id,accuracy,latitude,longitude,brand,name,city,state,locality
count,4081,1954.000000,4081.000000,4081.000000,4081,1089,1089,1089,1038
unique,4081,NaN,NaN,NaN,3,1089,68,17,1038
top,1400216,NaN,NaN,NaN,Blinkit,MUM-KASARVADAVALI,Bengaluru,Maharashtra,SNN Clermont
freq,1,NaN,NaN,NaN,1954,1,159,194,1
mean,NaN,22.216991,21.494433,77.842709,NaN,NaN,NaN,NaN,NaN
std,NaN,27.436712,6.285832,3.901752,NaN,NaN,NaN,NaN,NaN
min,NaN,0.000000,8.184644,69.642790,NaN,NaN,NaN,NaN,NaN
25%,NaN,0.000000,17.355889,75.829815,NaN,NaN,NaN,NaN,NaN
50%,NaN,25.000000,21.276136,77.384920,NaN,NaN,NaN,NaN,NaN
75%,NaN,39.000000,28.410694,78.572350,NaN,NaN,NaN,NaN,NaN
max,NaN,625.000000,32.766852,94.932671,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Brand Distribution

brand_counts = stores["brand"].value_counts()

brand_counts

brand
Blinkit             1954
Zepto               1089
Swiggy Instamart    1038
Name: count, dtype: int64

In [ ]:
import pandas as pd

stores = pd.read_csv("master_darkstores.csv")

print("Dataset loaded:", stores.shape)
stores.head()

Dataset loaded: (4081, 9)

      id  accuracy  latitude  longitude    brand name city state locality
0  42985      43.0  8.478260  76.954711  Blinkit  NaN  NaN   NaN      NaN
1  40038      13.0  8.525199  76.955395  Blinkit  NaN  NaN   NaN      NaN
2  38514      30.0  9.587031  76.535782  Blinkit  NaN  NaN   NaN      NaN
3  38406      48.0  9.922391  78.095686  Blinkit  NaN  NaN   NaN      NaN
4  39056       0.0  9.949993  76.253442  Blinkit  NaN  NaN   NaN      NaN

In [ ]:
# Percentage Distribution


(
stores["brand"]
.value_counts(normalize=True)
.mul(100)
.round(2)
)

brand
Blinkit             47.88
Zepto               26.68
Swiggy Instamart    25.43
Name: proportion, dtype: float64

In [ ]:
# NORTH–SOUTH GEOGRAPHIC SPREAD
# Full violin: spreads LEFT + RIGHT

import plotly.graph_objects as go

BRAND_COLORS = {
    "Blinkit": "#F8CB46",
    "Zepto": "#7A288A",
    "Swiggy Instamart": "#FC8019"
}

brand_order = [
    "Blinkit",
    "Zepto",
    "Swiggy Instamart"
]

fig = go.Figure()

for brand in brand_order:

    data = stores.loc[
        stores["brand"] == brand,
        "latitude"
    ].dropna()

    fig.add_trace(
        go.Violin(
            x=[brand] * len(data),
            y=data,

            orientation="v",

            # FULL violin — no side="positive"
            name=brand,

            line=dict(
                color=BRAND_COLORS[brand],
                width=2.2
            ),

            fillcolor=BRAND_COLORS[brand],
            opacity=0.60,

            box_visible=False,
            meanline_visible=False,
            points=False,

            width=0.75,

            hovertemplate=(
                f"<b>{brand}</b><br>"
                "Latitude: %{y:.2f}°N"
                "<extra></extra>"
            )
        )
    )

fig.update_layout(

    title=dict(
        text=(
            "<b>North–South Geographic Spread</b><br>"
            "<span style='font-size:13px;color:#777777'>"
            "Latitude concentration of each quick-commerce network"
            "</span>"
        ),
        x=0.5,
        xanchor="center",
        font=dict(size=23, color="#202124")
    ),

    xaxis=dict(
        title="",
        showgrid=False
    ),

    yaxis=dict(
        title="SOUTH  ↓   Latitude (°N)   ↑  NORTH",
        gridcolor="#EEEEEE",
        zeroline=False
    ),

    showlegend=False,

    plot_bgcolor="#FCFCFC",
    paper_bgcolor="white",

    width=1000,
    height=650,

    margin=dict(
        t=125,
        l=110,
        r=60,
        b=80
    )
)

fig.show()

In [ ]:
# EAST–WEST GEOGRAPHIC SPREAD
# Full violin: spreads UP + DOWN

import plotly.graph_objects as go

BRAND_COLORS = {
    "Blinkit": "#F8CB46",
    "Zepto": "#7A288A",
    "Swiggy Instamart": "#FC8019"
}

brand_order = [
    "Blinkit",
    "Zepto",
    "Swiggy Instamart"
]

fig = go.Figure()

for brand in brand_order:

    data = stores.loc[
        stores["brand"] == brand,
        "longitude"
    ].dropna()

    fig.add_trace(
        go.Violin(
            x=data,
            y=[brand] * len(data),

            orientation="h",

            # FULL violin — no side="positive"
            name=brand,

            line=dict(
                color=BRAND_COLORS[brand],
                width=2.2
            ),

            fillcolor=BRAND_COLORS[brand],
            opacity=0.60,

            box_visible=False,
            meanline_visible=False,
            points=False,

            width=0.75,

            hovertemplate=(
                f"<b>{brand}</b><br>"
                "Longitude: %{x:.2f}°E"
                "<extra></extra>"
            )
        )
    )

fig.update_layout(

    title=dict(
        text=(
            "<b>East–West Geographic Spread</b><br>"
            "<span style='font-size:13px;color:#777777'>"
            "Longitude concentration of each quick-commerce network"
            "</span>"
        ),
        x=0.5,
        xanchor="center",
        font=dict(size=23, color="#202124")
    ),

    xaxis=dict(
        title="WEST  ←   Longitude (°E)   →  EAST",
        gridcolor="#EEEEEE",
        zeroline=False
    ),

    yaxis=dict(
        title="",
        showgrid=False
    ),

    showlegend=False,

    plot_bgcolor="#FCFCFC",
    paper_bgcolor="white",

    width=1000,
    height=550,

    margin=dict(
        t=125,
        l=150,
        r=60,
        b=80
    )
)

fig.show()

In [ ]:

# Missing Values

stores.isnull().sum()

id              0
accuracy     2127
latitude        0
longitude       0
brand           0
name         2992
city         2992
state        2992
locality     3043
dtype: int64

In [ ]:
# Save Dataset

stores.to_csv(
    "eda_dataset.csv",
    index=False
)

print("✅ Exploratory Data Analysis Completed Successfully!")

✅ Exploratory Data Analysis Completed Successfully!

In [ ]:
import plotly.graph_objects as go

BRAND_COLORS = {
    "Blinkit": "#F8CB46",
    "Zepto": "#7A288A",
    "Swiggy Instamart": "#FC8019"
}

total_stores = brand_counts.sum()

fig = go.Figure()

for brand, count in brand_counts.items():

    share = count / total_stores * 100

    fig.add_trace(
        go.Bar(
            x=[brand],
            y=[count],
            marker=dict(
                color=BRAND_COLORS[brand],
                line=dict(color="white", width=2)
            ),
            text=f"<b>{count:,}</b><br>{share:.1f}%",
            textposition="outside",
            hovertemplate=(
                f"<b>{brand}</b><br>"
                f"Stores: {count:,}<br>"
                f"Network Share: {share:.1f}%"
                "<extra></extra>"
            ),
            showlegend=False
        )
    )

fig.update_layout(
    title=dict(
        text=(
            "<b>QUICK-COMMERCE NETWORK SCALE</b><br>"
            "<sup>Dark store distribution across competing brands</sup>"
        ),
        x=0.5
    ),

    xaxis_title="Brand",
    yaxis_title="Number of Dark Stores",

    plot_bgcolor="#FAFAFA",
    paper_bgcolor="white",

    yaxis=dict(
        gridcolor="#EAEAEA",
        zeroline=False
    ),

    height=520,
    margin=dict(t=110, l=80, r=50, b=70)
)

fig.show()

In [ ]:
%whos DataFrame

Variable   Type         Data/Info
---------------------------------
demand     DataFrame               id  accuracy  <...>\n[4081 rows x 9 columns]
stores     DataFrame               id  accuracy  <...>\n[4081 rows x 9 columns]